#!/bin/bash
sudo apt-get install mint-backgrounds-maya
sudo apt-get install mint-backgrounds-nadia
sudo apt-get install mint-backgrounds-olivia
sudo apt-get install mint-backgrounds-petra
sudo apt-get install mint-backgrounds-qiana
sudo apt-get install mint-backgrounds-rafaela
sudo apt-get install mint-backgrounds-rebecca
sudo apt-get install mint-backgrounds-retro
sudo apt-get install mint-backgrounds-rosa
sudo apt-get install mint-backgrounds-sarah
sudo apt-get install mint-backgrounds-serena
sudo apt-get install mint-backgrounds-sonya
sudo apt-get install mint-backgrounds-sylvia
sudo apt-get install mint-backgrounds-tara
sudo apt-get install mint-backgrounds-tessa
sudo apt-get install mint-backgrounds-tina
sudo apt-get install mint-backgrounds-tricia
sudo apt-get install mint-backgrounds-ulyana
sudo apt-get install mint-backgrounds-ulyssa
sudo apt-get install mint-backgrounds-uma
sudo apt-get install mint-backgrounds-una
sudo apt-get install mint-backgrounds-vanessa
sudo apt-get install mint-backgrounds-vera
sudo apt-get install mint-backgrounds-victoria
sudo apt-get install mint-backgrounds-virginia
